### ISSUE TITLE
problem with using oden undercroft and missing pieces

### ISSUE THREAD

**Issue by chrisanderso** [BentoGambin/Valheim-MissingPieces#4]
I noticed that some of the pieces from the oden undercroft mod are missing now it seems like they are not fitting because there's nor more space . I don't know what if anything you can do about that . btw thankyou for the fast updates .

**Comment by BentoGambin** [comment]
You can use this https://valheim.thunderstore.io/package/ComfyMods/ComfyBuildExpansion/
There are also other mods that add more space in a different way but I don't remember their name.
